# Generated by Django 5.2.3 on 2025-06-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='site_name',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='ativa',
            field=models.BooleanField(default=False, verbose_name='Ativa'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='config_name',
            field=models.CharField(default='Minha Configuração', max_length=100, verbose_name='minha configuração'),
        ),
    ]
