# Generated by Django 5.2.3 on 2025-06-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_app', '0003_historicalsiteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='Whatsapp'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='Whatsapp'),
        ),
    ]
