# Generated by Django 5.2.3 on 2025-06-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_app', '0004_historicalsiteconfig_whatsapp_siteconfig_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsiteconfig',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='SiteConfig',
        ),
        migrations.DeleteModel(
            name='HistoricalSiteConfig',
        ),
    ]
