version: "3.9"

services:
  web:
    build: .
    volumes:
      - ./media:/app/media
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - os7-net

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./staticfiles:/static
      - ./media:/media
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template
    environment:
      - DOMAIN=${DOMAIN}
    command: /bin/bash -c "envsubst < /etc/nginx/templates/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - web
    networks:
      - os7-net

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: os7db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: smvf5353
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - os7-net

volumes:
  postgres_data:

networks:
  os7-net:
    driver: bridge
