version: '3.8'

services:
  web:
    build: .
    entrypoint: ["sh", "/home/app/web/entrypoint.sh"]
    command: >
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static:/home/app/web/staticfiles
      - ./media:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  nginx:
    build: ./nginx
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./media:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data: