version: "3.9"

services:
  web:
    build: .
    volumes:
      - ./media:/app/media
    depends_on:
      - db
    networks:
      - os7-net

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    environment:
      DOMAIN: "meusite.com.br"
    volumes:
      - ./staticfiles:/static
      - ./media:/media
    depends_on:
      - web
    networks:
      - os7-net
    command:
      - /bin/sh
      - -c
      - |
        cat <<EOF > /etc/nginx/conf.d/default.conf
        server {
            listen 80;
            server_name ${DOMAIN};

            client_max_body_size 100M;

            location /static/ {
                alias /static/;
            }

            location /media/ {
                alias /media/;
            }

            location / {
                proxy_pass http://web:8000;
                proxy_set_header Host \$host;
                proxy_set_header X-Real-IP \$remote_addr;
                proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto \$scheme;
            }
        }
        EOF

        exec nginx -g 'daemon off;'
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: os7db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: smvf5353
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - os7-net

volumes:
  postgres_data:

networks:
  os7-net:
    driver: bridge
