version: '3.8'

services:
  web:
    build: .
    entrypoint: ["sh", "/home/app/web/entrypoint.sh"]
    command: >
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      web:
        condition: service_healthy

volumes:
  postgres_data:
  static_volume:
  media_volume: