version: "3.9"

services:
  web:
    build: .
    volumes:
      - ./media:/app/media
    depends_on:
      - db
    networks:
      - os7-net

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./staticfiles:/static
      - ./media:/media
    command: >
      /bin/bash -c "printf 'server {\n
        listen 80;\n
        server_name meusite.com.br;\n
        client_max_body_size 100M;\n
        location /static/ {\n
          alias /static/;\n
        }\n
        location /media/ {\n
          alias /media/;\n
        }\n
        location / {\n
          proxy_pass http://web:8000;\n
          proxy_set_header Host \$host;\n
          proxy_set_header X-Real-IP \$remote_addr;\n
          proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;\n
          proxy_set_header X-Forwarded-Proto \$scheme;\n
        }\n
      }\n' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - web
    networks:
      - os7-net

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: os7db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: smvf5353
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - os7-net

volumes:
  postgres_data:

networks:
  os7-net:
    driver: bridge
