# Generated by Django 5.2.3 on 2025-06-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsiteconfig',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Site Configuration', 'verbose_name_plural': 'historical Site Configurations'},
        ),
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': 'Site Configuration', 'verbose_name_plural': 'Site Configurations'},
        ),
        migrations.RemoveField(
            model_name='historicalsiteconfig',
            name='ativa',
        ),
        migrations.RemoveField(
            model_name='historicalsiteconfig',
            name='dias_atendimento',
        ),
        migrations.RemoveField(
            model_name='historicalsiteconfig',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='historicalsiteconfig',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='ativa',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='dias_atendimento',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='siteconfig',
            name='telefone',
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='business_hours',
            field=models.TextField(blank=True, null=True, verbose_name='Business Hours'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='historicalsiteconfig',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='business_hours',
            field=models.TextField(blank=True, null=True, verbose_name='Business Hours'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='historicalsiteconfig',
            name='config_name',
            field=models.CharField(default='My Configuration', max_length=100, verbose_name='Configuration Name'),
        ),
        migrations.AlterField(
            model_name='historicalsiteconfig',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='historicalsiteconfig',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='historicalsiteconfig',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='config_name',
            field=models.CharField(default='My Configuration', max_length=100, verbose_name='Configuration Name'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp'),
        ),
    ]
